'use client';

import { notFound } from 'next/navigation';
import Link from 'next/link';
import { use } from 'react';
import { SiReact, SiNextdotjs, SiJavascript, SiLaravel, SiDocker, SiKubernetes, SiSocketdotio, SiMui, SiNodedotjs, SiPython, SiTensorflow, SiMongodb, SiExpress, SiTailwindcss, SiRedux, SiAxios } from 'react-icons/si';
import { FaLayerGroup, FaGithub, FaExternalLinkAlt, FaCode, FaArrowLeft } from 'react-icons/fa';
import { motion, Variants } from 'framer-motion';

export const projects = [
  {
    id: 1,
    title: 'A Learning Platform for Programming',
    shortDescription: "A modern TryHackMe-inspired web platform for hands-on programming learning, with a VS Code extension for tracking effective coding time and syncing analytics, structured learning paths, progressive challenges, secure code evaluation, real-time interactivity, and gamification.",
    description: "A modern TryHackMe-inspired web platform for hands-on programming learning, with a VS Code extension for tracking effective coding time and syncing analytics, structured learning paths, progressive challenges, secure code evaluation, real-time interactivity, and gamification.",
    imageUrl: '/Devcash.png',
    keyFeatures: [
      'Coverage of multiple languages (Python, JavaScript/TypeScript, Java, C#, Go, Rust...) and diverse fields (Web, Mobile, API, Data Science, Game Development...)',
      'Built-in development environment with instant execution',
      'Structured learning experiences + passive challenges',
      'Safe automated code debugging (sandboxing)',
      'Gamification (points, levels, achievements, leaderboard)',
    ],
    vsCodeAddon: {
      title: 'VS Code Add-on (My Team Development)',
      description: 'Free Visual Studio Code add-on that measures effective programming time by:',
      features: [
        'Tracking project start time',
        'Number of code modifications',
        'Number of saves',
        'Reasons for successes after completion',
      ],
      footer: 'The add-on then calculates the effective source code and sends it to the platform for analysis and integration with the user\'s browser.',
    },
    techStack: [
      { icon: SiReact, name: 'React.js', color: 'text-blue-600' },
      { icon: SiNextdotjs, name: 'Next.js', color: 'text-black' },
      { icon: SiJavascript, name: 'JavaScript', color: 'text-yellow-500' },
      { icon: SiLaravel, name: 'Laravel', color: 'text-red-600' },
      { icon: SiDocker, name: 'Docker', color: 'text-blue-600' },
      { icon: SiKubernetes, name: 'Kubernetes', color: 'text-blue-700' },
      { icon: SiSocketdotio, name: 'WebSocket', color: 'text-black' },
      { icon: SiMui, name: 'Material-UI', color: 'text-blue-600' },
    ],
    links: { github: 'https://github.com/Engyahiadar/Devcash-Front-end', demo: '#' },
    hasCaseStudy: false,
  },
  {
    id: 2,
    title: 'High-Frequency Trading Platform', // حافظت على العنوان الأحدث/الأكثر دقة من المصفوفة الأولى
    shortDescription: 'A high-frequency trading platform supporting Spot and Futures markets, powered by a custom LSTM neural network trained on 6 years of historical market data.',
    description: 'A real-time trading platform UI for Spot and Futures markets, focused on high-performance dashboards, live price updates, and data visualization. Built interactive and responsive interfaces to display market data and AI-driven signals generated by an LSTM model trained on 6 years of historical data.',
    imageUrl: '/1cryptox.jpg',
    keyFeatures: [
      'High-performance dashboards for Spot and Futures markets',
      'Real-time price updates and live data streaming',
      'Advanced interactive data visualization (charts, graphs)',
      'Responsive and user-friendly interface across devices',
      'Integration of AI-driven trading signals from LSTM model',
      'Display of market data with low-latency updates',
    ],
    vsCodeAddon: null,
    techStack: [
      { icon: SiReact, name: 'React.js', color: 'text-blue-600' },
      { icon: SiNodedotjs, name: 'Node.js', color: 'text-green-600' },
      { icon: SiPython, name: 'Python', color: 'text-yellow-400' },
      { icon: SiTensorflow, name: 'TensorFlow', color: 'text-orange-500' },
      { icon: SiMongodb, name: 'MongoDB', color: 'text-green-500' },
      { icon: SiExpress, name: 'Express.js', color: 'text-gray-400' },
      { icon: SiTailwindcss, name: 'Tailwind CSS', color: 'text-sky-400' },
      { icon: SiMui, name: 'Material-UI', color: 'text-blue-600' },
      { icon: SiRedux, name: 'Redux Toolkit', color: 'text-purple-600' },
      { icon: SiAxios, name: 'Axios', color: 'text-purple-600' },
      { icon: SiSocketdotio, name: 'WebSocket', color: 'text-black' },
    ],
    links: { github: '#', demo: 'https://cryptox-ae9db.web.app' },
    hasCaseStudy: false,
  },
];

const containerVariants: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
      delayChildren: 0.2,
    },
  },
};

const sectionVariants: Variants = {
  hidden: { opacity: 0, y: 40 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.8, ease: 'easeOut' } },
};

export default function ProjectDetails({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params);
  const project = projects.find(p => p.id === Number(resolvedParams.id));

  if (!project) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-gray-200 text-gray-800 py-24 px-6">
      {/* Back Button */}
      <Link
        href="/#projects"
        className="inline-flex items-center gap-3 text-blue-600 hover:text-blue-800 transition mb-12 group"
      >
        <FaArrowLeft className="text-xl group-hover:-translate-x-2 transition" />
        <span className="font-medium">Back to Projects</span>
      </Link>

      <motion.div
        initial="hidden"
        animate="visible"
        variants={containerVariants}
        className="max-w-5xl mx-auto space-y-16"
      >
        {/* Title */}
        <motion.h1
          variants={sectionVariants}
          className="text-4xl md:text-6xl font-bold text-center text-gray-900"
        >
          {project.title}
        </motion.h1>

        {/* Description Card */}
        <motion.section
          variants={sectionVariants}
          className="bg-white rounded-2xl p-8 md:p-12 shadow-xl border border-gray-300"
        >
          <p className="text-lg md:text-xl leading-relaxed text-gray-700">{project.description}</p>
        </motion.section>

        {/* Key Features */}
        <motion.section variants={sectionVariants}>
          <h3 className="text-3xl md:text-4xl font-bold mb-10 text-center flex items-center justify-center gap-4 text-gray-900">
            <FaLayerGroup className="text-blue-600 text-4xl" />
            Key Features
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {project.keyFeatures.map((feature, idx) => (
              <motion.div
                key={idx}
                // whileHover={{ x: 10, }}
                className="flex items-start gap-4 bg-white rounded-xl p-6 shadow-md border border-gray-200 hover:shadow-xl transition-shadow"
              >
                <span className="text-blue-600 text-2xl mt-1">•</span>
                <span className="text-gray-700">{feature}</span>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* VS Code Add-on */}
        {project.vsCodeAddon && (
          <motion.section
            variants={sectionVariants}
            className="bg-white rounded-2xl p-8 md:p-12 shadow-xl border border-gray-300"
          >
            <h3 className="text-3xl md:text-4xl font-bold mb-8 text-center flex items-center justify-center gap-4 text-gray-900">
              <FaCode className="text-blue-600 text-4xl" />
              {project.vsCodeAddon.title}
            </h3>
            <p className="text-lg text-gray-700 mb-8">{project.vsCodeAddon.description}</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
              {project.vsCodeAddon.features.map((feature, idx) => (
                <div key={idx} className="flex items-start gap-4">
                  <span className="text-blue-600 text-2xl mt-1">•</span>
                  <span className="text-gray-700">{feature}</span>
                </div>
              ))}
            </div>
            <p className="text-gray-600 italic">{project.vsCodeAddon.footer}</p>
          </motion.section>
        )}

        {/* Tech Stack */}
        <motion.section variants={sectionVariants}>
          <h3 className="text-3xl md:text-4xl font-bold mb-12 text-center text-gray-900">
            Tech Stack
          </h3>
          <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-7 gap-8">
            {project.techStack.map((tech, idx) => (
              <motion.div
                key={idx}
                // whileHover={{ scale: 1.15, y: -10 }}
                className="group flex flex-col items-center"
              >
                <div className="bg-white rounded-2xl p-6 shadow-lg border border-gray-300 group-hover:border-blue-500 group-hover:shadow-2xl transition-all duration-500">
                  <tech.icon className={`text-5xl md:text-6xl ${tech.color}`} />
                </div>
                <p className="mt-4 text-sm md:text-base text-gray-700 font-medium group-hover:text-blue-600 transition">
                  {tech.name}
                </p>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* Links */}
        <motion.div
          variants={sectionVariants}
          className="flex flex-col sm:flex-row gap-8 justify-center pt-8"
        >
          <Link
            href={project.links.github}
            className="group flex items-center justify-center gap-4 bg-gray-800 text-white px-10 py-5 rounded-xl font-bold text-lg shadow-xl hover:bg-gray-900 hover:shadow-2xl transition-all duration-300"
          >
            <FaGithub className="text-2xl group-hover:rotate-12 transition" />
            View Code on GitHub
          </Link>
          <Link
            href={project.links.demo}
            className="group flex items-center justify-center gap-4 bg-blue-600 text-white px-10 py-5 rounded-xl font-bold text-lg shadow-xl hover:bg-blue-700 hover:shadow-2xl transition-all duration-300 "
          >
            <FaExternalLinkAlt className="text-2xl group-hover:translate-x-2 transition" />
            Live Demo
          </Link>
        </motion.div>
      </motion.div>
    </main>
  );
}